# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/china
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

#配置swagger
swagger:
  basePackage: com.shaochen.swaggerdemo.rest
  title: userDemo
  description: this is a userDemo.
  version: V1.0

#基础配置
appName: swagger测试
appIp: 127.0.0.1
